name: "Thank Contribution"
description: "Thanks constributors by commenting on their pull requests."
inputs:
  repo-token:
    description: "GITHUB_TOKEN"
    required: true
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: "message-square"
  color: "blue"
